version: '3.9'

services:
  prosgresDB:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"

    ports:
      - '55432:5432'

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: